### ISSUE TITLE
Is docker a requirement?

### ISSUE THREAD

**Issue by Stevemoretz** [net-byte/tcptun#1]
Hi thank you for this I needed to know wether this can be run without docker?

And it's the right tool for chaining servers like 

```
Client <---this-tool---> Server1 <---this-tool---> Server2 <---this-tool---> Server3
```

Also what is `-p 2000:2000` in the ReadMe it's not documented but used in examples

**Comment by net-byte** [comment]
No,It can be run without docker.Run the  binary file like this :
./tcptun-linux-amd64 -l :2000 -s server-ip:2001 -k 123456

-p 2000:2000 is a docker parameter for mapping port.
